version: '2'
services:
  postgres:
    image: mdillon/postgis:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=in
      - POSTGRES_PASSWORD=in
      - POSTGRES_DB=template_postgis
    volumes:
      - ./schema:/docker-entrypoint-initdb.d/:ro
  elastic:
    build: ./elastic
    image: conservify/inat-elastic
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
  server:
    build: ./server
    image: conservify/inat-server
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_ADDRESS=postgres
      - POSTGRES_USERNAME=in
      - POSTGRES_PASSWORD=in
      - POSTGRES_DB=inaturalist_development
    depends_on:
      - postgres
      - elastic
  api:
    build: ./api
    image: conservify/inat-api
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_ADDRESS=postgres
      - POSTGRES_USERNAME=in
      - POSTGRES_DB=inaturalist_development
    depends_on:
      - postgres
      - server
