login: &login
  host: <%= ENV['POSTGRES_ADDRESS'] %>
  encoding: utf8
  adapter: postgis
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  template: template_postgis

development:
  <<: *login
  database: inaturalist_development

test:
  <<: *login
  database: inaturalist_test

production:
  <<: *login
  database: inaturalist_production
